# Generated by Django 5.1.4 on 2024-12-26 07:32

import gallery.models.user_image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(upload_to=gallery.models.user_image.user_directory_path),
        ),
    ]
